# Generated by Django 2.1.7 on 2019-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_admincoupon_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='admincoupon',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
